# Generated by Django 5.0.6 on 2024-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.TextField(verbose_name='note')),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
